# -*- coding: utf-8 -*-
# Copyright (C) 2005 José Pablo Ezequiel "Pupeno" Fernández Silva
#
# This file is part of scons-chicken.
#
# Scons-chicken is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
# Scons-chicken is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with scons-chicken; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA

# Create an environment including the scons-chicken tool.
lib = Environment(tools = ["default", "chicken"], toolpath=["../../"])
# The previous line is to use the non-installed scons-chicken. In your project use:
# env = Environment(tools = ["default", "chicken"])

# Copy the lib environment before altering it for only building libraries. This new environment, prg, will be altered for building programs.
prg = lib.Copy()

# Check if a Chicken library can be built (and try to alter the environment for that porpouse).
conf = Configure(lib, custom_tests = {"CheckChickenLibrary" : lib.CheckChickenLibrary})
if not conf.CheckChickenLibrary():
    print "It seems you don't have Chicken installed or it is not"
    print "installed correctly. For more information:"
    print "http://www.call-with-current-continuation.org/"
    Exit(1)
lib = conf.Finish()

# sc-ofl.so made of sc-ofl.scm.
sc_lapl = lib.SharedLibrary("sc-lapl.scm", SHLIBPREFIX="")
lib.Install(lib["CHICKENREPOSITORY"], sc_lapl)

# setup file for sc-lapl.
sc_lapl_setup = lib.ChickenSetup(sc_lapl, meta = {"version" : [0, 1, 99]})
lib.Install(lib["CHICKENREPOSITORY"], sc_lapl_setup)

# Install alias
#lib.Alias("install", env["CHICKENREPOSITORY"])

# Build an egg.
lib.ChickenEgg(sc_lapl)

# Check if a Chicken program can be built (and try to alter the environment for that porpouse).
conf = Configure(prg, custom_tests = {"CheckChickenProgram" : prg.CheckChickenProgram})
if not conf.CheckChickenProgram():
    print "It seems you don't have Chicken installed or it is not"
    print "installed correctly. For more information:"
    print "http://www.call-with-current-continuation.org/"
    Exit(1)
prg = conf.Finish()

sc_lapp = prg.Program("sc-lapp.scm")
prg.Install("/usr/bin/", sc_lapp)

# Install alias
#prg.Alias("install", "/usr/bin/")

# Build an egg.
lib.ChickenEgg(sc_lapp)
