# -*- coding: utf-8 -*-
# Copyright (C) 2005 José Pablo Ezequiel "Pupeno" Fernández Silva
#
# This file is part of scons-chicken.
#
# Scons-chicken is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
# Scons-chicken is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with scons-chicken; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA

# Create an environment including the scons-chicken tool.
env = Environment(tools = ["default", "chicken"], toolpath=["../../"])
# The previous line is to use the non-installed scons-chicken. In your project use:
# env = Environment(tools = ["default", "chicken"])

# Check if a Chicken program can be built (and try to alter the environment for that porpouse).
conf = Configure(env, custom_tests = {"CheckChickenProgram" : env.CheckChickenProgram})
if not conf.CheckChickenProgram():
    print "It seems you don't have Chicken installed or it is not"
    print "installed correctly. For more information:"
    print "http://www.call-with-current-continuation.org/"
    Exit(1)
env = conf.Finish()

# sc-mfp composed of sc-mfp1.scm y sc-mfp2.scm.
sc_mfp = env.Program("sc-mfp", ["sc-mfp1.scm", "sc-mfp2.scm"])
env.Install("/usr/bin", sc_mfp)

# Install alias.
#env.Alias("install", "/usr/bin")

# Build an egg
env.ChickenEgg(sc_mfp)
