# -*- coding: utf-8 -*-
# Copyright (C) 2005 José Pablo Ezequiel "Pupeno" Fernández Silva
#
# This file is part of scons-chicken.
#
# Scons-chicken is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
# Scons-chicken is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with scons-chicken; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA

# Create an environment including the scons-chicken tool.
env = Environment(tools = ["default", "chicken"], toolpath=["../../"])
# The previous line is to use the non-installed scons-chicken. In your project use:
# env = Environment(tools = ["default", "chicken"])

# Check if a Chicken library can be built (and try to alter the environment for that porpouse).
conf = Configure(env, custom_tests = {"CheckChickenLibrary" : env.CheckChickenLibrary})
if not conf.CheckChickenLibrary():
    print "It seems you don't have Chicken installed or it is not"
    print "installed correctly. For more information:"
    print "http://www.call-with-current-continuation.org/"
    Exit(1)
env = conf.Finish()

# sc-mfl.so composed of sc-mfl1.scm y sc-mfl2.scm.
sc_mfl = env.SharedLibrary("sc-mfl", ["sc-mfl1.scm", "sc-mfl2.scm"], SHLIBPREFIX="")
env.Install(env['CHICKENREPOSITORY'], sc_mfl)

# setup file for sc-mfl.
sc_mfl_setup = env.ChickenSetup(sc_mfl, REQUIRES=["sc-ofl"])
env.Install(env['CHICKENREPOSITORY'], sc_mfl_setup)

# Install alias.
#env.Alias('install', env['CHICKENREPOSITORY'])
