# -*- coding: utf-8 -*-
# Copyright (C) 2005 José Pablo Ezequiel "Pupeno" Fernández Silva
#
# This file is part of scons-chicken.
#
# scons-chicken is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
# scons-chicken is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with scons-chicken; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA

# Create an environment including the scons-chicken tool.
env = Environment(tools = ["default", "chicken"], toolpath=["../../"])
# The previous line is to use the non-installed scons-chicken. In your project use:
# env = Environment(tools = ["default", "chicken"])

# sc-mfl1.so composed of sc-mfl1.scm y sc-mfl2.scm.
sc_mfl1, sc_mfl1_setup = env.ChickenExtension(env,
                                              "sc-mfl1",
                                              ["sc-mfl1.scm", "sc-mfl2.scm"])

# sc-mfl3.so composed of sc-mfl3.scm y sc-mfl4.scm.
#sc_mfl3, sc_mfl3_setup = env.ChickenExtension(env,
#                                              "sc-mfl3", 
#                                              ["sc-mfl3.scm", "sc-mfl4.scm"])

# Install the .so files and the .setup file on the extension directory.
env.Install(env['CHICKENREPOSITORY'], sc_mfl1)
env.Install(env['CHICKENREPOSITORY'], sc_mfl1_setup)
#env.Install(env['CHICKENREPOSITORY'], sc_mfl3)
#env.Install(env['CHICKENREPOSITORY'], sc_mfl3_setup)
env.Alias('install', env['CHICKENREPOSITORY'])
