# -*- coding: utf-8 -*-
# Copyright (C) 2005 José Pablo Ezequiel "Pupeno" Fernández Silva
#
# This file is part of SCons Chicken.
#
# SCons Chicken is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
# SCons Chicken is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with SCons Chicken; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA

# Create an environment including the SCons Chicken tool.
env = Environment(tools = ["default", "chicken"], toolpath=["../../"])
# The previous line is to use the non-installed SCons Chicken. In your project use:
# env = Environment(tools = ["default", "chicken"])

# Check if a Chicken program can be built (and try to alter the environment for that porpouse).
conf = Configure(env, custom_tests = {"CheckChickenProgram" : env.CheckChickenProgram})
#if not conf.CheckChickenProgram():
#    print "It seems you don't have Chicken installed or it is not"
#    print "installed correctly. For more information:"
#    print "http://www.call-with-current-continuation.org/"
#    Exit(1)
env = conf.Finish()

# sc-sap (executable binary) made of sc-sap.scm.
sc_sap = env.Program("sc-sap.scm")
env.Install('/usr/bin/', sc_sap)

# Install alias.
#env.Alias('install', '/usr/bin/')

# Build an egg. It doesn't really make sense because eggs are only for libraries, not for programs. Another reason of why Eggs taste bad.
#env.ChickenEgg(sc_sap)
